version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: weather-rabbit
    ports:
      - "25080:15672"   # UI do RabbitMQ
      - "5672:5672"     # Comunicação AMQP
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
    command: >
      rabbitmq-server
      --load_definitions=/etc/rabbitmq/definitions.json

  mongo:
    image: mongo:7.0
    container_name: weather-mongo
    ports:
      - "55080:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: weatherapp
      MONGO_INITDB_ROOT_PASSWORD: weatherapp
      MONGO_INITDB_DATABASE: weatherapp
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: weather-redis
    ports:
      - "63790:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

volumes:
  mongo_data:
  rabbitmq_data:
  redis_data: