version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "25080:15672"   # UI do RabbitMQ
      - "56720:5672"     # Comunicação AMQP
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
    command: >
      rabbitmq-server
      --load_definitions=/etc/rabbitmq/definitions.json

  mongo:
    image: mongo:7.0
    container_name: propagandus-mongo
    ports:
      - "55080:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: propagandus_user
      MONGO_INITDB_ROOT_PASSWORD: propagandus_pass
      MONGO_INITDB_DATABASE: propagandus_db
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: propagandus-redis
    ports:
      - "63790:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

volumes:
  mongo_data:
  rabbitmq_data:
  redis_data: