spring:
  port: ${APP_PORT:50001}

data:
  mongodb:
    uri: ${MONGODB_URI:mongodb://weatherapp:weatherapp@localhost:55080/weatherapp?authSource=admin}

rabbitmq:
  host: ${RABBITMQ_HOST:localhost}
  port: ${RABBITMQ_PORT:5672}
  username: ${RABBITMQ_USERNAME:guest}
  password: ${RABBITMQ_PASSWORD:guest}
  virtual-host: ${RABBITMQ_VHOST:/}
